"""rename address

Revision ID: 373f357ca9ad
Revises: 3970dab99a98
Create Date: 2024-04-06 08:28:27.519953

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '373f357ca9ad'
down_revision = '3970dab99a98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
     op.alter_column('departments', 'address',  new_column_name='location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'location', new_column_name='address')
    # ### end Alembic commands ###
