"""add Department

Revision ID: 75023e0b3710
Revises: 08eedf689e9d
Create Date: 2024-04-06 08:13:51.080344

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75023e0b3710'
down_revision = '08eedf689e9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('department')
    # ### end Alembic commands ###
